#!/usr/bin/env ruby

# Copyright (c) 2013 <mattias.wadman@gmail.com>
#
# MIT License:
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# This script is work in progress but mean to be used to send code coverage
# reports to coveralls.io for Xcode based projects

require "open3"
require "pathname"
require "tmpdir"
require "tempfile"
require 'net/https'
require "json"
require "cgi"
require "uri"

# TODO:
# cli mode to output stats
# repo token support

def xcodebuild_build_settings(target, objroot)
  settings = {}

  # format:
  # NAME = VALUE
  _in, out, _err = Open3.popen3("xcodebuild -target \"#{target}\" -showBuildSettings \"OBJROOT=#{objroot}\"")
  while not out.eof? do
    case out.readline
    when /^\s*(.*) = (.*)$/ then settings[$1] = $2
    end
  end

  settings
end

def git_commit_info(rev)
  Hash[[[:id, "%H"],
        [:author_name, "%an"],
        [:author_email, "%ae"],
        [:committer_name, "%cn"],
        [:committer_email, "%ce"],
        [:message, "%s"]].map do |key, format|
          cmd = ["git", "--no-pager", "show", "-s", "--format=#{format}", rev]
          _in, out, _err = Open3.popen3(*cmd)
          [key, out.read.strip]
        end]
end

def git_branch_for_name(name)
  cmd = ["git", "rev-parse", "--abbrev-ref", name]
  _in, out, _err = Open3.popen3(*cmd)
  out.read.strip
end

def git_remotes
  remotes = {}

  cmd = ["git", "remote", "-v"]
  _in, out, _err = Open3.popen3(*cmd)
  while not out.eof? do
    case out.readline
    when /^(.+)\t([^ ]+) \(fetch\)/
      next if $1 == "kerne"
      remotes[$1] = $2
    end
  end

  remotes
end

def parse_gcov(gcov_string)
  coverage = []
  source_lines = []
  headers = {}

  gcov_string.lines.each do |line|
    case line
    # format:
    #        -:    0:Key:Value has line number 0
    #        8:    1:executed line
    #    #####:    2:non-executed line
    #        -:    3:whitespace/comment line etc
    when /^\s*(-|\d+|#####):\s*(\d+):(.*)$/
      linenumber = $2.to_i

      if linenumber == 0
        keyvalue = $3
        key, value = keyvalue.split(":", 2)
        headers[key] = value
      else
        times = $1
        source_line = $3

        coverage.push(
          case times
          when "-" then nil
          when "#####" then 0
          when /\d+/ then times.to_i
          end
        )

        source_lines.push(source_line)
      end
    end

  end

  {:headers => headers,
   :coverage => coverage,
   :source_lines => source_lines}
end

def gcov(object_dir, source_paths)
  gcovs = []

  # run gcov in temp directory
  Dir.mktmpdir do |dir|
    Dir.chdir(dir) do
      cmd = [
        "gcov",
        "--preserve-paths",
        "--object-directory", object_dir
      ] + source_paths
      _in, out, _err = Open3.popen3(*cmd)
      while not out.eof? do
        # TODO: check for error?
        out.readline
      end

      Dir.glob("*") do |file|
        gcovs.push(parse_gcov(open(file).read()))
      end
    end
  end

  gcovs
end

def coveralls_data(gcovs, source_root)
  gcovs.select! {|gcov| gcov[:headers]["Source"].start_with? source_root}
  source_root = source_root[0..-2] if source_root.end_with? "/"

  data = {
    :git => {
      :head => git_commit_info("HEAD"),
      :branch => (ENV["TRAVIS_BRANCH"] or git_branch_for_name("HEAD")),
      :remotes => git_remotes.map do |name, url|
        {:name => name,
         :url => url}
      end
    },
    :source_files => gcovs.map do |gcov|
      {:name => gcov[:headers]["Source"][source_root.length+1..-1],
       :source => gcov[:source_lines].join("\n"),
       :coverage => gcov[:coverage]}
    end
  }

  # TODO: required when not travis? argument?
  #data[:repo_token] = ""

  travis_job_id = ENV["TRAVIS_JOB_ID"]
  if travis_job_id
    data[:service_name] = "travis-ci"
    data[:service_job_id] = travis_job_id
  else
    data[:service_name] = "test"
  end

  data
end

def build_multipart_request(parts)
  useragent = "gcoveralls"
  boundary = "boundary"
  content_type = "multipart/form-data; boundary=#{boundary}"
  headers = {"Content-Type" => content_type, "User-Agent" => useragent}

  body = parts.collect do |part|
    [
      "--" + boundary,
      "Content-Disposition: form-data; name=\"#{CGI::escape(part[:name])}\"; filename=\"#{part[:filename]}\"",
      "Content-Type: #{part[:content_type]}",
      "",
      part[:content],
      ""
    ].join("\r\n")
  end.join("") + "--" + boundary + "--"

  return headers, body
end

def coveralls_submit(coveralls_data)
  uri = URI("https://coveralls.io/api/v1/jobs")
  req = Net::HTTP.new(uri.host, uri.port)
  req.use_ssl = true

  begin
    req.start do |c|
      headers, body = build_multipart_request([{
        :name => "json_file",
        :filename => "json_file",
        :content_type => "application/octet-stream",
        :content => JSON.generate(coveralls_data),
      }])

      # TODO: retry?
      res = c.post(uri.path, body, headers)
      if res.body
        coveralls_res = JSON::parse(res.body)
        if coveralls_res.has_key? "error"
          return false, coveralls_res["message"]
        else
          return true, "#{coveralls_res["message"]} #{coveralls_res["url"]}"
        end
      else
        return false, res.message
      end

    end
  rescue StandardError => e
    return false, e
  end
end

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

#srcroot = settings["SRCROOT"]

settings = xcodebuild_build_settings(ARGV[0], ARGV[1])
source_paths = Dir["**/*.{m,c,cpp,c++,mm}"]
gcov_data_path = File.join(settings["OBJECT_FILE_DIR_normal"], settings["CURRENT_ARCH"])

result, message = coveralls_submit(coveralls_data(gcov(gcov_data_path, source_paths), Dir.getwd))
puts "#{result ? "OK" : "Failed"}: #{message}"

